### ISSUE TITLE
The test set ID retriever doesn't work because the last 10% of the IDs are grabbed and indexed from 0 to N*0.1-1, but in the dataset I think they are indexed from N*0.9+1 to N. I just added -1800 in the code, but should probably actually fix it. 

### ISSUE THREAD

**Issue by annkennedy** [neuroethology/MARS_Developer#28]

**Comment by 404ic** [comment]
Not sure why but subtracting 0.9*dataset_size doesn't always work — it seems like the ID and frame number are not always associated in a regular way. Should add more robust method to figure out how to relate the ID of image in test set with the actual frame number.

**Comment by annkennedy** [comment]
I think I have fixed this now, there was a commented line in the test code that shouldn't have been commented.

To explain what's going on: in the MARS_tutorial notebook, `frame_num` is train/val/test-set-specific, ranging between 0 and K for some K (eg N*0.1-1 in the test set.) For some images, this is different from their original "`image number`" in the dataset (eg the test set is typically image numbers N-K+1 to N.) When testing is run, MARS extracts images from the test tfrecord, and saves them in `annotation_data/test_sets/<detector name>`, with a filename starting test `<frame_num>_image<image number>_<orginal filename>`.
